services:
  chromadb:
    image: dockerhub.timeweb.cloud/chromadb/chroma:latest
    container_name: nornickel_chroma
    restart: always
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma/
      - ANONYMIZED_TELEMETRY=False
    volumes:
      - chroma_data:/chroma/chroma/
volumes:
  chroma_data:
